
import type { VocabularyItem } from './types';

export const MAX_QUESTIONS = 10;

export const VOCABULARY: VocabularyItem[] = [
    { english: "apple", japanese: "りんご", emoji: "🍎" },
    { english: "cat", japanese: "ねこ", emoji: "🐱" },
    { english: "dog", japanese: "いぬ", emoji: "🐶" },
    { english: "book", japanese: "本", emoji: "📚" },
    { english: "school", japanese: "学校", emoji: "🏫" },
    { english: "teacher", japanese: "先生", emoji: "👩‍🏫" },
    { english: "friend", japanese: "友達", emoji: "👫" },
    { english: "pen", japanese: "ペン", emoji: "🖊️" },
    { english: "pencil", japanese: "鉛筆", emoji: "✏️" },
    { english: "desk", japanese: "机", emoji: " desks" },
    { english: "chair", japanese: "椅子", emoji: "🪑" },
    { english: "bag", japanese: "カバン", emoji: "🎒" },
    { english: "car", japanese: "車", emoji: "🚗" },
    { english: "bus", japanese: "バス", emoji: "🚌" },
    { english: "train", japanese: "電車", emoji: "🚆" },
    { english: "bike", japanese: "自転車", emoji: "🚲" },
    { english: "house", japanese: "家", emoji: "🏠" },
    { english: "tree", japanese: "木", emoji: "🌳" },
    { english: "flower", japanese: "花", emoji: "🌸" },
    { english: "sun", japanese: "太陽", emoji: "☀️" },
    { english: "moon", japanese: "月", emoji: "🌙" },
    { english: "star", japanese: "星", emoji: "⭐" },
    { english: "sky", japanese: "空", emoji: "☁️" },
    { english: "eat", japanese: "食べる", emoji: "🍔" },
    { english: "drink", japanese: "飲む", emoji: "🥤" },
    { english: "play", japanese: "遊ぶ、する", emoji: "🎮" },
    { english: "run", japanese: "走る", emoji: "🏃" },
    { english: "jump", japanese: "跳ぶ", emoji: "🤸" },
    { english: "swim", japanese: "泳ぐ", emoji: "🏊" },
    { english: "sing", japanese: "歌う", emoji: "🎤" },
    { english: "dance", japanese: "踊る", emoji: "💃" },
    { english: "read", japanese: "読む", emoji: "📖" },
    { english: "write", japanese: "書く", emoji: "✍️" },
    { english: "listen", japanese: "聞く", emoji: "👂" },
    { english: "speak", japanese: "話す", emoji: "🗣️" },
    { english: "look", japanese: "見る", emoji: "👀" },
    { english: "see", japanese: "見る、会う", emoji: "👁️" },
    { english: "study", japanese: "勉強する", emoji: "📚" },
    { english: "clean", japanese: "掃除する", emoji: "🧹" },
    { english: "wash", japanese: "洗う", emoji: "🧼" },
    { english: "cook", japanese: "料理する", emoji: "👩‍🍳" },
    { english: "make", japanese: "作る", emoji: "🔨" },
    { english: "help", japanese: "助ける", emoji: "🙏" },
    { english: "go", japanese: "行く", emoji: "🚶" },
    { english: "come", japanese: "来る", emoji: "👋" },
    { english: "stop", japanese: "止まる", emoji: "🛑" },
    { english: "like", japanese: "好き", emoji: "❤️" },
    { english: "love", japanese: "大好き", emoji: "🥰" },
    { english: "want", japanese: "欲しい", emoji: "✨" },
    { english: "big", japanese: "大きい", emoji: "🐘" },
    { english: "small", japanese: "小さい", emoji: "🐁" },
    { english: "long", japanese: "長い", emoji: "📏" },
    { english: "short", japanese: "短い", emoji: "🤏" },
    { english: "happy", japanese: "幸せな", emoji: "😄" },
    { english: "sad", japanese: "悲しい", emoji: "😢" },
    { english: "good", japanese: "良い", emoji: "👍" },
    { english: "bad", japanese: "悪い", emoji: "👎" },
    { english: "red", japanese: "赤", emoji: "🔴" },
    { english: "blue", japanese: "青", emoji: "🔵" },
    { english: "green", japanese: "緑", emoji: "🟢" },
    { english: "yellow", japanese: "黄", emoji: "🟡" },
    { english: "white", japanese: "白", emoji: "⚪" },
    { english: "black", japanese: "黒", emoji: "⚫" },
    { english: "one", japanese: "１", emoji: "1️⃣" },
    { english: "two", japanese: "２", emoji: "2️⃣" },
    { english: "three", japanese: "３", emoji: "3️⃣" },
    { english: "four", japanese: "４", emoji: "4️⃣" },
    { english: "five", japanese: "５", emoji: "5️⃣" },
    { english: "six", japanese: "６", emoji: "6️⃣" },
    { english: "seven", japanese: "７", emoji: "7️⃣" },
    { english: "eight", japanese: "８", emoji: "8️⃣" },
    { english: "nine", japanese: "９", emoji: "9️⃣" },
    { english: "ten", japanese: "１０", emoji: "🔟" },
    { english: "hello", japanese: "こんにちは", emoji: "👋" },
    { english: "good morning", japanese: "おはよう", emoji: "☀️" },
    { english: "good afternoon", japanese: "こんにちは (午後)", emoji: "☀️" },
    { english: "good evening", japanese: "こんばんは", emoji: "🌆" },
    { english: "goodbye", japanese: "さようなら", emoji: "👋" },
    { english: "thank you", japanese: "ありがとう", emoji: "😊" },
    { english: "excuse me", japanese: "すみません", emoji: "🙇" },
    { english: "sorry", japanese: "ごめんなさい", emoji: "😔" },
    { english: "please", japanese: "お願いします", emoji: "🙏" },
    { english: "yes", japanese: "はい", emoji: "✅" },
    { english: "no", japanese: "いいえ", emoji: "❌" },
    { english: "what's your name?", japanese: "お名前は何ですか？", emoji: "❓" },
    { english: "my name is...", japanese: "私の名前は...", emoji: "👤" },
    { english: "how are you?", japanese: "お元気ですか？", emoji: "🙂" },
    { english: "I'm fine", japanese: "元気です", emoji: "👍" },
    { english: "how old are you?", japanese: "何歳ですか？", emoji: "🎂" },
    { english: "I am eight years old.", japanese: "私は8歳です。", emoji: "8️⃣" },
    { english: "in front of", japanese: "〜の前に", emoji: "➡️" },
    { english: "a lot of", japanese: "たくさんの〜", emoji: "➕" },
    { english: "wait for", japanese: "〜を待つ", emoji: "⏳" },
    { english: "next to", japanese: "〜の隣に", emoji: "↔️" },
    { english: "go out", japanese: "外出する", emoji: "🚶" },
    { english: "at home", japanese: "家で", emoji: "🏠" },
    { english: "get up", japanese: "起きる", emoji: "⏰" },
    { english: "go to bed", japanese: "寝る", emoji: "🛌" },
    { english: "wash hands", japanese: "手を洗う", emoji: "🧼" },
    { english: "brush teeth", japanese: "歯を磨く", emoji: "🦷" },
    { english: "clean up", japanese: "片付ける", emoji: "🧹" }
];
